const express=require('express')
const Route=express.Router()
const{signup,getsignup,getlogin,postlogin,userdisplay,getuser,donate,savepayment, alldonation}=require('../controllers/userControllers')
const {auth}=require('../middlewere/auth')
Route.get('/',getsignup)
Route.post('/postsignup',signup)
Route.get('/getlogin',getlogin)
Route.post('/postlogin',postlogin)
Route.get('/userdisplay',userdisplay)
Route.get('/getuser',auth,getuser)
Route.post('/donate',donate)
Route.post('/savepayment',auth,savepayment)
Route.get('/alldonation',auth,alldonation)
module.exports=Route
